# Generated by Django 4.2.6 on 2025-08-29 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('province', models.CharField(choices=[('BAS-UELE', 'Bas-Uele'), ('EQUATEUR', 'Équateur'), ('HAUT-KATANGA', 'Haut-Katanga'), ('HAUT-LOMAMI', 'Haut-Lomami'), ('HAUT-UELE', 'Haut-Uele'), ('ITURI', 'Ituri'), ('KASAI', 'Kasaï'), ('KASAI-CENTRAL', 'Kasaï-Central'), ('KASAI-ORIENTAL', 'Kasaï-Oriental'), ('KINSHASA', 'Kinshasa'), ('KONGO-CENTRAL', 'Kongo-Central'), ('KWANGO', 'Kwango'), ('KWILU', 'Kwilu'), ('LOMAMI', 'Lomami'), ('LUALABA', 'Lualaba'), ('MAI-NDOMBE', 'Mai-Ndombe'), ('MANIEMA', 'Maniema'), ('MONGALA', 'Mongala'), ('NORD-KIVU', 'Nord-Kivu'), ('NORD-UBANGI', 'Nord-Ubangi'), ('SANKURU', 'Sankuru'), ('SUD-KIVU', 'Sud-Kivu'), ('SUD-UBANGI', 'Sud-Ubangi'), ('TANGANYIKA', 'Tanganyika'), ('TSHOPO', 'Tshopo'), ('TSHUAPA', 'Tshuapa')], max_length=30)),
                ('categorie', models.CharField(choices=[('Membre Honneur', "Membre d'Honneur"), ('Membre Effectif', 'Membre Effectif'), ('Membre Fondateur', 'Membre Fondateur'), ('Membre Co-fondateur', 'Membre Co-fondateur')], max_length=20)),
                ('fonction', models.CharField(blank=True, default='Membre', max_length=15, null=True)),
                ('site', models.CharField(blank=True, max_length=150, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('date_enregistrement', models.DateField(default=django.utils.timezone.now)),
                ('date_mise_a_jour', models.DateField(auto_now=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('carte_renouvelee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'post_nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Duplicata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('numero_carte', models.CharField(max_length=100)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicata_set', to='identification.membre')),
            ],
        ),
    ]
