# Generated by Django 4.2.6 on 2025-08-29 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('motif', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percu_par', models.CharField(max_length=100)),
                ('type_operation', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(default=django.utils.timezone.now)),
                ('montant', models.IntegerField()),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='identification.membre')),
            ],
            options={
                'ordering': ['-date_paiement'],
                'unique_together': {('membre', 'mois')},
            },
        ),
    ]
